### ISSUE TITLE
Thanks for this

### ISSUE THREAD

**Issue by tyeeman** [Nicify/nvtool#1]
Just downloaded to try out. Been looking for a GUI version of Rigayas' CLI. Just wondering if encoding 4k are all the color space info, HDR info, etc. all copied to the new encoding? It would be nice to see the command line generated by your app, and be able to add anything desired.

**Comment by tyeeman** [comment]
Just tried this for the first time, and it says downloading NVEncC, but I already put it in the same folder?
I click run and there is no indication anything is running. I click cancel and the program closes totally. 
Please indicate what I'm doing wrong?

**Comment by Nicify** [comment]
Hi there!
Thanks for trying this GUI.
The command line format used within the GUI is "--codec %s --profile high --audio-copy --preset %s --vbr %v --vbr-quality %v --max-bitrate 60000 --bframes 4 --ref 16 --lookahead 32 --gop-len 250 --%s --aq-strength %v", color space info, HDR info are not processed yet.

As for CBR, it is not supported yet. I think the overall quality of the encoding mode in NVENC is CQP > VBR > CBR for the same output file size. CBR guarantees a stable bitrate not quality, especially for videos with many dynamic scenes, such as videos recorded by FPS and racing games. 

The advantage of CBR is that the output file size can be controlled more precisely and is suitable for broadcasting at a fixed bitrate, while CQP and VBR are better choices for recording and transcoding video

To use mkv just change the extension of the file in the Output input to .mkv before encoding and it will be automatically encapsulated using the mkv container

"Constant quality" is described in https://github.com/rigaya/NVEnc/blob/master/NVEncC_Options.en.md#--vbr-int.
NVEnc has an actual 'Constant Quality' mode equivalent to x264's CRF (https://github.com/HandBrake/HandBrake/issues/2231#issue-479031649) by setting mode to VBR, and set cq, qmin, qmax to the same value.

**Comment by Nicify** [comment]
This GUI is a work-in-progress and may lack certain features at this stage, such as HDR, CQP, CBR mode, more filters and manual setting of command line parameters. This will be improved in subsequent development.

**Comment by tyeeman** [comment]
Great, thanks for the info. Keep up the great work here. One suggestion that would probably take care of my requests while you add other features would be to save command lines that have been added to manually, then load them at any time. Having all items in the command line as widgets is probably not necessary like you mentioned above.

Here is my 1080p command line I've been using for about 1 year. Let me know if you see how it can be improved (maybe your current settings are even better?)

--cbr 6000 --codec h265 --multipass none --preset quality --profile main10 --tier high --level 4.1 --output-depth 10 --vpp-edgelevel strength=9,threshold=12 --bframes 2 --ref 4 --gop-len 150 --lookahead 32 --aq --qp-init 1 --cuda-schedule auto --mv-precision q-pel --colorrange auto --colormatrix auto --colorprim auto --transfer auto --max-cll copy --master-display copy --videoformat auto --chromaloc auto --vpp-unsharp weight=1.5,radius=3 --vpp-gauss 3 --crop 0,0,0,0 --seek 0:00:00.000 -i "video.mkv" -o "videoEncode.h265"

**Comment by tyeeman** [comment]
Just noticed on the new version 2.5, clicking the down arrow for Preset and AQ will not show the list until the cursor is moved off the arrow.

**Comment by Nicify** [comment]
This should be a problem with the gui framework itself, I'll look into it, thanks for reporting the issue.
